dist: trusty
sudo: false
notifications:
  email: change

language: rust

rust:
  - nightly

cache:
    cargo: true
    apt: true

script:
    - cd deucalion-rs
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc --verbose

addons:
  apt:
    packages:
     - libsfml-dev
     - libcsfml-dev
