[package]
name = "deucalion-rs"
version = "0.1.0"
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]

[dependencies]
hlua = "0.4"
sfml = "0.14"
log = "0.4"
env_logger = "0.5"
tiled = "0.7"
update_rate = "1"
euclid = "0.17"